name: default
version: 1
description: Default DesignSpec workflow
artifacts:
  - id: proposal
    generates: proposal.md
    description: Initial proposal document outlining the change
    template: proposal.md
    instruction: |
      Do something
    requires: []

  - id: screens
    generates: screens.md
    description: Screens
    template: screens.md
    instruction: |
      Do something
    requires:
      - proposal
